namespace Linn.Stores.IoC
{
    using System.Collections.Generic;

    using Linn.Common.Reporting.Resources.ReportResultResources;
    using Linn.Common.Resources;
    using Linn.Common.Service.Core.Handlers;
    using Linn.Stores.Domain.LinnApps.Wand.Models;
    using Linn.Stores.Resources;
    using Linn.Stores.Resources.Allocation;
    using Linn.Stores.Resources.Consignments;
    using Linn.Stores.Resources.GoodsIn;
    using Linn.Stores.Resources.ImportBooks;
    using Linn.Stores.Resources.Parts;
    using Linn.Stores.Resources.Requisitions;
    using Linn.Stores.Resources.Scs;
    using Linn.Stores.Resources.StockLocators;
    using Linn.Stores.Resources.Tpk;
    using Linn.Stores.Resources.Tqms;
    using Linn.Stores.Resources.Wand;
    using Linn.Stores.Resources.Workstation;
    using Linn.Stores.Service.ResultHandlers;

    using Microsoft.Extensions.DependencyInjection;

    public static class HandlerExtensions
    {
        public static IServiceCollection AddHandlers(this IServiceCollection services)
        {
            return services
                .AddTransient<IHandler, JsonResultHandler<ExportReturnResource>>()
                .AddTransient<IHandler, JsonResultHandler<ReportReturnResource>>()
                .AddTransient<IHandler, CsvResultHandler<ReportReturnResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<AccountingCompanyResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesArticleResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ImportBookCpcNumberResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ImportBookDeliveryTermResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<InspectedStateResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ProcessResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<BookInResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<IntercompanyInvoiceResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<IntercompanyInvoiceResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PartStorageTypeResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<LoanDetailResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<LoanResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PartTqmsOverrideResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PortResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ProductAnalysisCodeResource>>>()
                .AddTransient<IHandler, JsonResultHandler<RequisitionProcessResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<RequisitionResource>>()
                .AddTransient<IHandler, JsonResultHandler<SalesOutletResource>>()
                .AddTransient<IHandler, JsonResultHandler<PartTemplateResource>>()
                .AddTransient<IHandler, JsonResultHandler<RequisitionActionResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesArticleResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesOutletResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<AuditLocationResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<AssemblyTechnologyResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesAccountResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<RootProductResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<RsnAccessoryResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<RsnConditionResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<RsnResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ConsignmentResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ConsignmentResource>>>()
                .AddTransient<IHandler, JsonResultHandler<SalesAccountResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesAccountResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<CountryResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<CurrencyResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<DecrementRuleResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<DepartmentResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<DespatchLocationResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<EmployeeResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<NominalAccountResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockLocatorResource>>>()
                .AddTransient<IHandler, JsonResultHandler<PartTemplateResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PartTemplateResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ScsPalletResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockMoveResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockPoolResource>>>()
                .AddTransient<IHandler, JsonResultHandler<TpkResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SernosSequenceResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ShippingTermResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ShippingTermResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SosAllocHeadResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<AvailableStockResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StoresBudgetPostingResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StoresTransactionDefinitionResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SupplierResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockLocatorPricesResource>>>()
                .AddTransient<IHandler, JsonResultHandler<StockLocatorResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockLocatorResource>>>()
                .AddTransient<IHandler, JsonResultHandler<NominalResource>>()
                .AddTransient<IHandler, RequisitionMovesResultHandler>()
                .AddTransient<IHandler, JsonResultHandler<StoragePlaceResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StoragePlaceResource>>>()
                .AddTransient<IHandler, JsonResultHandler<PackingListResource>>()
                .AddTransient<IHandler, JsonResultHandler<StockTriggerLevelsResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockTriggerLevelsResource>>>()
                .AddTransient<IHandler, JsonResultHandler<SosAllocDetailResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SosAllocDetailResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StorageLocationResource>>>()
                .AddTransient<IHandler, JsonResultHandler<SalesOutletResource>>()
                .AddTransient<IHandler, JsonResultHandler<StockQuantitiesResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<StockQuantitiesResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesOutletResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<TqmsCategoryResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<TqmsJobRefResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<TransferableStockResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<WandConsignmentResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<WandItemResource>>>()
                .AddTransient<IHandler, JsonResultHandler<TqmsMasterResource>>()
                .AddTransient<IHandler, JsonResultHandler<ValidatePurchaseOrderResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<ValidateRsnResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<ValidateStorageTypeResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<WandItemResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<WorkstationTopUpStatusResource>>()
                .AddTransient<IHandler, JsonResultHandler<WarehouseLocationResource>>()
                .AddTransient<IHandler, JsonResultHandler<WhatToWandConsignmentResource>>()
                .AddTransient<IHandler, JsonResultHandler<ParcelResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ParcelResource>>>()
                .AddTransient<IHandler, JsonResultHandler<PurchaseOrderResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PurchaseOrderResource>>>()
                .AddTransient<IHandler, JsonResultHandler<AllocationResource>>()
                .AddTransient<IHandler, JsonResultHandler<MechPartSourceResource>>()
                .AddTransient<IHandler, JsonResultHandler<PartLiveTestResource>>()
                .AddTransient<IHandler, JsonResultHandler<PartResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PartResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<UnitOfMeasureResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ErrorResource>>()
                .AddTransient<IHandler, JsonResultHandler<MessageResource>>()
                .AddTransient<IHandler, JsonResultHandler<PartLibraryResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PartLibraryResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ExportReturnResource>>()
                .AddTransient<IHandler, JsonResultHandler<ExportRsnResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ExportRsnResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<PartDataSheetValuesResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ManufacturerResource>>>()
                .AddTransient<IHandler, JsonResultHandler<DespatchPalletQueueResultResource>>()
                .AddTransient<IHandler, JsonResultHandler<SalesAccountResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesAccountResource>>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<SalesOutletResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ImportBookResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ImportBookResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ImportBookTransportCodeResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ImportBookTransportCodeResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ImportBookTransactionCodeResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ImportBookTransactionCodeResource>>>()
                .AddTransient<IHandler, JsonResultHandler<CarrierResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<CarrierResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ImportBookExchangeRateResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ImportBookExchangeRateResource>>>()
                .AddTransient<IHandler, JsonResultHandler<HubResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<HubResource>>>()
                .AddTransient<IHandler, JsonResultHandler<ConsignmentShipfileResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<ConsignmentShipfileResource>>>()
                .AddTransient<IHandler, JsonResultHandler<CartonTypeResource>>()
                .AddTransient<IHandler, JsonResultHandler<IEnumerable<CartonTypeResource>>>();
        }
    }
}
